#!/usr/bin/env python3
"""
INDEX - Scripts d'analyse de configuration
Exécutez ce script pour voir la liste de tous les outils disponibles.
"""

print()
print("=" * 80)
print(" INDEX - ANALYSE CRITIQUE CONFIGURATION YAML ".center(80))
print("=" * 80)
print()
print("Scripts disponibles dans temp_tests/:")
print()
print("1️⃣  analyze_config_params.py")
print("    → Analyse automatique (scan + grep)")
print("    → Détection paramètres obsolètes/non utilisés")
print("    💡 Exécuter en premier pour vue d'ensemble rapide")
print()
print("2️⃣  dashboard_config.py")
print("    → Tableau de bord synthétique visuel")
print("    → Statistiques + résumé par sévérité")
print("    💡 Vue d'ensemble en 1 page")
print()
print("3️⃣  analyse_finale_config.py")
print("    → Rapport détaillé par problème")
print("    → Explications techniques approfondies")
print("    💡 Pour comprendre chaque problème en détail")
print()
print("4️⃣  propositions_corrections_config.py")
print("    → Solutions recommandées")
print("    → Justifications et alternatives")
print("    💡 Guide pour appliquer les corrections")
print()
print("5️⃣  recap_config.py")
print("    → Récapitulatif complet")
print("    → Plan d'action en 3 phases")
print("    💡 Vue méthodologique globale")
print()
print("6️⃣  README_ANALYSE_CONFIG.md")
print("    → Documentation markdown")
print("    💡 À lire pour comprendre le projet")
print()
print("=" * 80)
print(" UTILISATION RECOMMANDÉE ".center(80))
print("=" * 80)
print()
print("Pour première découverte:")
print("  1. python temp_tests/dashboard_config.py      # Vue synthétique")
print("  2. python temp_tests/recap_config.py          # Récapitulatif complet")
print()
print("Pour analyse approfondie:")
print("  3. python temp_tests/analyse_finale_config.py # Détail par problème")
print("  4. python temp_tests/propositions_corrections_config.py # Solutions")
print()
print("Pour vérification automatique:")
print("  5. python temp_tests/analyze_config_params.py # Scan automatisé")
print()
print("=" * 80)
print(" RÉSUMÉ DES RÉSULTATS ".center(80))
print("=" * 80)
print()
print("Problèmes identifiés: 7 paramètres (sur 56 total)")
print()
print("  🔴 MAJEUR (2):")
print("    - entente_facteur_reduction (conflit logique)")
print("    - qualite_match (code mort, 4 params)")
print()
print("  🟡 MINEUR (2):")
print("    - nb_preferences_gymnases (redondant)")
print("    - aller_retour_min_semaines (non utilisé)")
print()
print("  🔵 INFO (1):")
print("    - calendrier (4 params, décision utilisateur)")
print()
print("Impact: ~250 lignes de code à supprimer, 4 fichiers à modifier")
print("Risque: 🟢 Très faible (code mort/redondant)")
print()
print("=" * 80)
print()
